name: Lint, test and deploy
on: push
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

  dependencies:
    needs: get-code
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Deploying ...'
